### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by finesse357** [TitansBane/Elysium-Remastered#79]
Cannot continue, was unable to download one or more archives 
[Wabbajack.00.log](https://github.com/TitansBane/Elysium-Remastered/files/9614394/Wabbajack.00.log)
[Wabbajack.01.log](https://github.com/TitansBane/Elysium-Remastered/files/9614395/Wabbajack.01.log)
[Wabbajack.02.log](https://github.com/TitansBane/Elysium-Remastered/files/9614396/Wabbajack.02.log)
[Wabbajack.03.log](https://github.com/TitansBane/Elysium-Remastered/files/9614397/Wabbajack.03.log)
[Wabbajack.current.log](https://github.com/TitansBane/Elysium-Remastered/files/9614400/Wabbajack.current.log)
I'm totally new so I guess I'm posting my issue here the steps to follow for this issue were quite unclear and I had no network workaround option in my Wabbajack. I tried restarting it a couple times but nothing to it

**Comment by Decodas** [comment]
I had the same issue when I tried to install it today. The modlist is for Skyrim SE 1.6.353, but a few days ago Skyrim SE 1.6.640 has been released. Since the modlist comes with it's own stockgame that shouldn't be a problem, but it seems Wabbajack trys to download the newer version which leads to the hash mismatches in the logs.

I was able to resolve this by downloading Skyrim SE 1.6.353, afterwards I put the whole game in a new directory named "Skyrim Special Edition", inside Wabbajack's download location. 
Afterwards the installation worked without errors for me.
I downloaded a cracked version of Skyrim to get back to version 1.6.353, since it was easier to find. Because of that crack I won't post a link here.


> I had no network workaround option in my Wabbajack

If you had with some instructions, it's probably because Wabbajack also had an update and it was a pretty big one so quite few things changed since the tutorial was written. The new version 3.0.1.4 is, according to their Discord, backwards compatible and I had no problems during the install. If you prefer an older version, so the instructions match better, you can download it [here](https://github.com/wabbajack-tools/wabbajack/releases). I think the instructions are written for version 2.5.3.28.

**Comment by GeneralCalobe** [comment]
> I had the same issue when I tried to install it today. The modlist is for Skyrim SE 1.6.353, but a few days ago Skyrim SE 1.6.640 has been released. Since the modlist comes with it's own stockgame that shouldn't be a problem, but it seems Wabbajack trys to download the newer version which leads to the hash mismatches in the logs.
> 
> I was able to resolve this by downloading Skyrim SE 1.6.353, afterwards I put the whole game in a new directory named "Skyrim Special Edition", inside Wabbajack's download location. Afterwards the installation worked without errors for me. I downloaded a cracked version of Skyrim to get back to version 1.6.353, since it was easier to find. Because of that crack I won't post a link here.
> 
> > I had no network workaround option in my Wabbajack
> 
> If you had problems with some instructions, it's probably because Wabbajack also had an update and it was a pretty big one so quite few things changed since the tutorial was written. The new version 3.0.1.4 is, according to their Discord, backwards compatible and I had no problems during the install. If you prefer an older version, so the instructions match better, you can download it [here](https://github.com/wabbajack-tools/wabbajack/releases). I think the instructions are written for version 2.5.3.28.

So I was able to find the version that you were talking about, and did what you recommended but am still running into the issue similar to what was described in the original post. Any other Ideas that you may have to try and resolve this issue? Any input would be greatly appreciated!

[Wabbajack.09.log](https://github.com/TitansBane/Elysium-Remastered/files/9642496/Wabbajack.09.log)
[Wabbajack.10.log](https://github.com/TitansBane/Elysium-Remastered/files/9642497/Wabbajack.10.log)
[Wabbajack.11.log](https://github.com/TitansBane/Elysium-Remastered/files/9642494/Wabbajack.11.log)
[Wabbajack.current.log](https://github.com/TitansBane/Elysium-Remastered/files/9642495/Wabbajack.current.log)

**Comment by Snowman1109** [comment]
Hey im also having the same issue as [alvarengando][finesse357] i tried running FullPatcher_1.6.640.0-1.6.353.0.exe-57618-2022-09-20-1663702315 off nexus but i still failed with the same errors 

[FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download SkyrimSE.exe (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|skyrimse.exe)     onwards with other files

i have also tried replacing the exe just like [Decodas] has stated that has failed on other files. has anyone managed to get this working and if so any insight would be great thank you

**Comment by Snowman1109** [comment]
I got mine working. @finesse357 @alvarengando I'm not sure if you know as I wasn't aware this is a AE mod list, make sure your game is the upgraded anniversary edition. Then once you have AE downloaded on steam launch the game and press play so it downloads the extra content then you can close it and run wabbajack mod list.  It is all explained on the preinstallation and setup bit but nothing on wabbajack  about been AE so to any devs you might want to make it clear on the wabbajack Info bio if they miss this information on your website.
