### ISSUE TITLE
Elwaps and Mega file download links

### ISSUE THREAD

**Issue by rperezandreiuk** [TitansBane/Elysium-Remastered#8]
Could anyone please post here links to the main MEGA files of Elysium Remastered Modlist? Specially Elwaps and Main file.
My discord account is having a problem with my telephone number updating process.
Thanks a lot!!

**Comment by rperezandreiuk** [comment]
1. Elwaps Speedtree;
2. Dyndolod 3D output; 
3. Core files.

These are the files I cannot find. Could anyone please put the links to download them manually? 
Thanks in advance.

**Comment by TheClock69** [comment]
Hey, yo man. I tried all of the methods on the internet, and attended the discord (I can recommend for their support! - Wabbajack discord). 

The thing that actually worked for me, earlier on this week. Deleting Skyrim - wiping all of the files - even on docs. Deleting the WJ Mod downloads, and starting completely fresh. 

I know it can seem like a bane, after the big 150GB download, but I think it was totally worth it, in my case. (remember to redownload the CC content). 

All the best, and good luck!

**Comment by rperezandreiuk** [comment]
Hey, bro. Thanks a lot for your valuable feedback. I´m definetely trying that.
Cheers!

**Comment by TheClock69** [comment]
> Hey, bro. Thanks a lot for your valuable feedback. I´m definetely trying that. Cheers!

Lemme know if it worked! 😄🙏

**Comment by rperezandreiuk** [comment]
Hey, man!
It didn´t work, unfortunately. I did reset everything: WJ, files at DOCs, skyrim, modlists, etc.
It gives me a 2 file problem (before there were three):
Dyndolod and Core files. Elwaps did work smoothly.

![Skyrim error screenshot](https://user-images.githubusercontent.com/87189048/157544703-366f2cf7-ec65-4622-8030-ebac21787db6.png)

I will try again. If fact, I am trying in this exact moment ;-)
Meanwhile, do you know if it is possible to download them manually?
Thanks again, bro.

**Comment by TheClock69** [comment]
Heya, 
Okay - did you validate files, with steam? 
Also, downloaded CC content prior.

I found the manual download file through one genorous... guy on the WJ discord (e.remastered support page). So, yes, it is possible - although the consensus was even after the 14gb manual download, it still failed.

I had a couple of days of problems - reset with network turnaround off, and like 1 network band available, and maybe 7 cpu bands open... then... it worked with the entire reset. So... good luck, and otherwise - I highly recommend and suggest heading to WJ discord :)

All the best!

TheClock69

**Comment by rperezandreiuk** [comment]
Yeah man...
Unfortunately, nobody answers my questions at Discord.
Tried through Wabbajack channels, Elysium roles and etc.
Also, elysium-remastered-support channel is archived. 
And, just noticed Elysium modlist is out of WJ.

Thanks anyway for your attention, bro.
